=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/xml/Pins.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root fileElement -->
<!ELEMENT root (family, pins, packages, peripherals) >
   <!ATTLIST root version CDATA #REQUIRED >

 <!ELEMENT family (device)* >
   <!ATTLIST family name        CDATA #REQUIRED>
   
 <!ELEMENT device EMPTY >
   <!ATTLIST device name        CDATA #REQUIRED>
   <!ATTLIST device manual      CDATA #REQUIRED>
   <!ATTLIST device package     CDATA #REQUIRED>
   
 <!ELEMENT pins (pin*) >
 
 <!ELEMENT pin (mux*, (reset, default)?) >
   <!ATTLIST pin name        CDATA #REQUIRED>
   <!ATTLIST pin isFixed     (true|false) "false">
   
 <!ELEMENT mux EMPTY >
   <!ATTLIST mux sel         (reset|fixed|mux0|mux1|mux2|mux3|mux4|mux5|mux6|mux7|disabled) #REQUIRED>
   <!ATTLIST mux function    CDATA #REQUIRED>
   
 <!ELEMENT reset EMPTY >
   <!ATTLIST reset sel         (reset|fixed|mux0|mux1|mux2|mux3|mux4|mux5|mux6|mux7|disabled) #REQUIRED>
   
 <!ELEMENT default EMPTY >
   <!ATTLIST default sel         (reset|fixed|mux0|mux1|mux2|mux3|mux4|mux5|mux6|mux7|disabled) #REQUIRED>
   
 <!ELEMENT packages (package*) >
   
 <!ELEMENT package (placement*) >
   <!ATTLIST package name        CDATA #REQUIRED>
 
 <!ELEMENT placement EMPTY >
   <!ATTLIST placement pin        CDATA #REQUIRED>
   <!ATTLIST placement location   CDATA #REQUIRED>
   
 <!ELEMENT peripherals (peripheral*) >
   
 <!ELEMENT peripheral (clock*,irq*,dma?) >
   <!ATTLIST peripheral name        CDATA #REQUIRED>
 
 <!ELEMENT pcrs (pcr*) >

 <!ELEMENT clock EMPTY >
   <!ATTLIST clock clockReg        CDATA #REQUIRED>
   <!ATTLIST clock clockMask       CDATA #REQUIRED>

 <!ELEMENT irq EMPTY >
   <!ATTLIST irq num        CDATA #REQUIRED>
    
 <!ELEMENT pcr EMPTY >
   <!ATTLIST pcr index        CDATA #REQUIRED>
   <!ATTLIST pcr function     CDATA #REQUIRED>
   
 <!ELEMENT dma (slot*) >

 <!ELEMENT slot EMPTY >
   <!ATTLIST slot source  CDATA #REQUIRED>
   <!ATTLIST slot num     CDATA #REQUIRED>

=== PatrickFulcheri/usbdm-eclipse-plugins/CreateTemplatedCppStationery/xml/pin_mapping-MKE06Z4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "Pins.dtd">
<!-- pin_mapping-MKE06Z4.xml -->
<!-- 
   Generated from MKE06Z4.csv
-->

<root version="1.2.0">
   <family name="MKE06Z4">
      <device name="MKE06Z4-FRDM" manual="MKE06P80M48SF0RM" package="FRDM" />
      <device name="MKE06Z4-LQFP80" manual="MKE06P80M48SF0RM" package="LQFP-80" />
   </family>
   <pins>
      <pin name="PTA0">
         <mux sel="mux0"          function="GPIOA_0" />
         <mux sel="mux1"          function="KBI0_P0" />
         <mux sel="mux2"          function="FTM0_CH0" />
         <mux sel="mux3"          function="I2C0_4WSCLOUT" />
         <mux sel="mux4"          function="ACMP0_IN0" />
         <mux sel="mux5"          function="ADC0_SE0" />
         <reset sel="mux5" />
         <default sel="mux5" />
      </pin>
      <pin name="PTA1">
         <mux sel="mux0"          function="GPIOA_1" />
         <mux sel="mux1"          function="KBI0_P1" />
         <mux sel="mux2"          function="FTM0_CH1" />
         <mux sel="mux3"          function="I2C0_4WSDAOUT" />
         <mux sel="mux4"          function="ACMP0_IN1" />
         <mux sel="mux5"          function="ADC0_SE1" />
         <reset sel="mux5" />
         <default sel="mux5" />
      </pin>
      <pin name="PTA2">
         <mux sel="mux0"          function="GPIOA_2" />
         <mux sel="mux1"          function="KBI0_P2" />
         <mux sel="mux2"          function="UART0_RX" />
         <mux sel="mux3"          function="I2C0_SDA" />
         <reset sel="disabled" />
         <default sel="disabled" />
      </pin>
      <pin name="PTA3">
         <mux sel="mux0"          function="GPIOA_3" />
         <mux sel="mux1"          function="KBI0_P3" />
         <mux sel="mux2"          function="UART0_TX" />
         <mux sel="mux3"          function="I2C0_SCL" />
         <reset sel="disabled" />
         <default sel="disabled" />
      </pin>
      <pin name="PTA4">
         <mux sel="mux0"          function="GPIOA_4" />
         <mux sel="mux1"          function="KBI0_P4" />
         <mux sel="mux3"          function="ACMP0_OUT" />
         <mux sel="mux4"          function="SWD_DIO" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTA5">
         <mux sel="mux0"          function="GPIOA_5" />
         <mux sel="mux1"          function="KBI0_P5" />
         <mux sel="mux2"          function="IRQ" />
         <mux sel="mux3"          function="TCLK0" />
         <mux sel="mux4"          function="RESET_b" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTA6">
         <mux sel="mux0"          function="GPIOA_6" />
         <mux sel="mux1"          function="KBI0_P6" />
         <mux sel="mux2"          function="FTM2_FLT1" />
         <mux sel="mux3"          function="ACMP1_IN0" />
         <mux sel="mux4"          function="ADC0_SE2" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTA7">
         <mux sel="mux0"          function="GPIOA_7" />
         <mux sel="mux1"          function="KBI0_P7" />
         <mux sel="mux2"          function="FTM2_FLT2" />
         <mux sel="mux3"          function="ACMP1_IN1" />
         <mux sel="mux4"          function="ADC0_SE3" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTB0">
         <mux sel="mux0"          function="GPIOA_8" />
         <mux sel="mux1"          function="KBI0_P8" />
         <mux sel="mux2"          function="UART0_RX" />
         <mux sel="mux3"          function="PWT_IN1" />
         <mux sel="mux4"          function="ADC0_SE4" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTB1">
         <mux sel="mux0"          function="GPIOA_9" />
         <mux sel="mux1"          function="KBI0_P9" />
         <mux sel="mux2"          function="UART0_TX" />
         <mux sel="mux4"          function="ADC0_SE5" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTB2">
         <mux sel="mux0"          function="GPIOA_10" />
         <mux sel="mux1"          function="KBI0_P10" />
         <mux sel="mux2"          function="SPI0_SCK" />
         <mux sel="mux3"          function="FTM0_CH0" />
         <mux sel="mux4"          function="ADC0_SE6" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTB3">
         <mux sel="mux0"          function="GPIOA_11" />
         <mux sel="mux1"          function="KBI0_P11" />
         <mux sel="mux2"          function="SPI0_MOSI" />
         <mux sel="mux3"          function="FTM0_CH1" />
         <mux sel="mux4"          function="ADC0_SE7" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTB4">
         <mux sel="mux0"          function="GPIOA_12" />
         <mux sel="mux1"          function="KBI0_P12" />
         <mux sel="mux2"          function="FTM2_CH4" />
         <mux sel="mux3"          function="SPI0_MISO" />
         <mux sel="mux4"          function="ACMP1_IN2" />
         <mux sel="mux5"          function="NMI_b" />
         <reset sel="mux5" />
         <default sel="mux5" />
      </pin>
      <pin name="PTB5">
         <mux sel="mux0"          function="GPIOA_13" />
         <mux sel="mux1"          function="KBI0_P13" />
         <mux sel="mux2"          function="FTM2_CH5" />
         <mux sel="mux3"          function="SPI0_PCS" />
         <mux sel="mux4"          function="ACMP1_OUT" />
         <reset sel="disabled" />
         <default sel="disabled" />
      </pin>
      <pin name="PTB6">
         <mux sel="mux0"          function="GPIOA_14" />
         <mux sel="mux1"          function="KBI0_P14" />
         <mux sel="mux2"          function="I2C0_SDA" />
         <mux sel="mux6"          function="XTAL" />
         <reset sel="mux6" />
         <default sel="mux6" />
      </pin>
      <pin name="PTB7">
         <mux sel="mux0"          function="GPIOA_15" />
         <mux sel="mux1"          function="KBI0_P15" />
         <mux sel="mux2"          function="I2C0_SCL" />
         <mux sel="mux6"          function="EXTAL" />
         <reset sel="mux6" />
         <default sel="mux6" />
      </pin>
      <pin name="PTC0">
         <mux sel="mux0"          function="GPIOA_16" />
         <mux sel="mux1"          function="KBI0_P16" />
         <mux sel="mux2"          function="FTM2_CH0" />
         <mux sel="mux4"          function="ADC0_SE8" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTC1">
         <mux sel="mux0"          function="GPIOA_17" />
         <mux sel="mux1"          function="KBI0_P17" />
         <mux sel="mux2"          function="FTM2_CH1" />
         <mux sel="mux4"          function="ADC0_SE9" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTC2">
         <mux sel="mux0"          function="GPIOA_18" />
         <mux sel="mux1"          function="KBI0_P18" />
         <mux sel="mux2"          function="FTM2_CH2" />
         <mux sel="mux4"          function="ADC0_SE10" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTC3">
         <mux sel="mux0"          function="GPIOA_19" />
         <mux sel="mux1"          function="KBI0_P19" />
         <mux sel="mux2"          function="FTM2_CH3" />
         <mux sel="mux4"          function="ADC0_SE11" />
         <reset sel="mux4" />
         <default sel="mux4" />
      </pin>
      <pin name="PTC4">
         <mux sel="mux0"          function="GPIOA_20" />
         <mux sel="mux1"          function="KBI0_P20" />
         <mux sel="mux2"          function="RTC_CLKOUT" />
         <mux sel="mux3"          function="FTM1_CH0" />
         <mux sel="mux4"          function="ACMP0_IN2" />
         <mux sel="mux5"          function="SWD_CLK" />
         <reset sel="mux5" />
         <default sel="mux5" />
      </pin>
      <pin name="PTC5">
         <mux sel="mux0"          function="GPIOA_21" />
         <mux sel="mux1"          function="KBI0_P21" />
         <mux sel="mux3"          function="FTM1_CH1" />
         <mux sel="mux5"          function="RTC_CLKOUT" />
         <reset sel="disabled" />
         <default sel="disabled" />
      </pin>
      <pin name="PTC6">
         <mux sel="mux0"          function="GPIOA_22" />
         <mux sel="mux1"          function="KBI0_P22" />
         <mux sel="mux2"          function="UART1_RX" />
         <mux sel="mux5"          function="CAN0_RX" />
         <reset sel="disabled" />
         <default sel="disabled" />
      </pin>
      <pin name="PTC7">
         <mux sel="mux0"          function="GPIOA_23" />
         <mux sel="mux1"          function="KBI0_P23" />
         <mux sel="mux2"          function="UART1_TX" />
         <mux sel="mux5"          function="CAN0_TX" />
         <reset sel="disabled" />
         <default sel="disabled" />
      </pin>
      <pin name="PTD0">
         <mux sel="mux0"          function="GPIOA_24" />
         <mux sel="mux1"          function="KBI0_P24" />
         <mux sel="mux2"          function="FTM2_CH2" />
         <mux sel="mux3"          function="SPI1_SCK" />
         <reset sel="disabled" />
         <default sel="disabled" />
      </pin>
      <pin name="PTD1">
         <mux sel="mux0"          function="GPIOA_25" />
         <mux sel="mux1"          function="KBI0_P25" />
         <mux sel="mux2"          function="FTM2_CH3" />
         <mux sel="mux3"          function="SPI1_MOSI" />
         <reset sel="disabled" />
         <default sel="disabled" />
      </pin>
      <pin name="PTD2">
         <mux sel="mux0"          function="GPIOA_26" />
         <mux sel="mux1"          function="KBI0_P26" />
         <mux sel="mux2"          function="SPI1_MISO" />
