=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/_menu.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % gui_items        "(xi:include|category|constant|floatOption|intOption|bitmaskOption|choiceOption|binaryOption|stringOption|numericListOption|pinListOption|aliasOption|signals)" >
<!ENTITY % structure_items  "((section*)|(tab)*)" >
<!ENTITY % control_items    "(xi:include|template|validate|projectActionList)" >

<!-- Include another file -->
<!ELEMENT xi:include EMPTY>
   <!ATTLIST xi:include href      CDATA        #REQUIRED>

<!-- Root fileElement -->
<!ELEMENT devicePage (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST devicePage xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST devicePage name         CDATA        #REQUIRED>
   <!ATTLIST devicePage description  CDATA        #REQUIRED>
   <!ATTLIST devicePage toolTip      CDATA        "">

<!ELEMENT fragment ANY >
   <!ATTLIST fragment xmlns:xi CDATA #IMPLIED>

<!ELEMENT section (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST section name         CDATA        #IMPLIED>

<!ELEMENT tab (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST tab name         CDATA        #REQUIRED>

<!ELEMENT category ((%gui_items;)*) >
   <!ATTLIST category xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST category name         CDATA        #REQUIRED>
   <!ATTLIST category description  CDATA        #REQUIRED>
   <!ATTLIST category toolTip      CDATA        "">


<!ELEMENT intOption EMPTY >
   <!ATTLIST intOption constant     (false|true) "false">
   <!ATTLIST intOption name         ID           #REQUIRED>
   <!ATTLIST intOption key          CDATA        #IMPLIED>
   <!ATTLIST intOption origin       CDATA        #IMPLIED>
   <!ATTLIST intOption description  CDATA        #IMPLIED>
   <!ATTLIST intOption toolTip      CDATA        "">
   <!ATTLIST intOption value        CDATA        "0">
   <!ATTLIST intOption units        (None|Hz|s)  "None">
   <!ATTLIST intOption step         CDATA        "1">
   <!-- Minimum value (displayed value) -->
   <!ATTLIST intOption min          CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST intOption max          CDATA        #IMPLIED>
   <!-- Offset to translate from displayed value to substitution value -->
   <!ATTLIST intOption offset       CDATA        "0">
   <!ATTLIST intOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST intOption derived      (false|true) "false">
   <!ATTLIST intOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT bitmaskOption EMPTY >
   <!ATTLIST bitmaskOption constant      (false|true) "false">
   <!ATTLIST bitmaskOption name          ID           #REQUIRED>
   <!ATTLIST bitmaskOption key           CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption origin        CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption description   CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption toolTip       CDATA        "">
   <!ATTLIST bitmaskOption value         CDATA        "0">
   <!ATTLIST bitmaskOption bitmask       CDATA        "0xFFFF">
   <!ATTLIST bitmaskOption bitList       CDATA        "">
   <!ATTLIST bitmaskOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption derived       (false|true) "false">
   <!ATTLIST bitmaskOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT floatOption EMPTY >
   <!ATTLIST floatOption constant     (false|true) "false">
   <!ATTLIST floatOption name         ID           #REQUIRED>
   <!ATTLIST floatOption key          CDATA        #IMPLIED>
   <!ATTLIST floatOption origin       CDATA        #IMPLIED>
   <!ATTLIST floatOption description  CDATA        #IMPLIED>
   <!ATTLIST floatOption toolTip      CDATA        "">
   <!ATTLIST floatOption value        CDATA        "0">
   <!ATTLIST floatOption units        (None|Hz|s)  "None">
   <!-- Minimum value (displayed value) -->
   <!ATTLIST floatOption min          CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST floatOption max          CDATA        #IMPLIED>
   <!ATTLIST floatOption derived      (false|true) "false">
   <!ATTLIST floatOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT aliasOption EMPTY >
   <!-- alias Option 
   name 		Refers to another option within the same file and will be used as key and validated as a reference to an ID
   key  		Allows reference to an option (possibly) in another file while passing validation
   displayName	Allows the name of the model (visible in the GUI) to differ from the aliased option's name
   -->
   <!ATTLIST aliasOption name        IDREF        #IMPLIED>
   <!ATTLIST aliasOption key         CDATA        #IMPLIED>
   <!ATTLIST aliasOption displayName CDATA        #IMPLIED>
   <!ATTLIST aliasOption description CDATA        #IMPLIED>
   <!ATTLIST aliasOption toolTip     CDATA        #IMPLIED>
   <!ATTLIST aliasOption constant    (false|true) "true">
   <!ATTLIST aliasOption optional    (false|true) "false">

<!ELEMENT stringOption EMPTY >
   <!ATTLIST stringOption constant     (false|true) "false">
   <!ATTLIST stringOption name         ID           #REQUIRED>
   <!ATTLIST stringOption key          CDATA        #IMPLIED>
   <!ATTLIST stringOption origin       CDATA        #IMPLIED>
   <!ATTLIST stringOption description  CDATA        #IMPLIED>
   <!ATTLIST stringOption toolTip      CDATA        "">
   <!ATTLIST stringOption value        CDATA        "0">
   <!ATTLIST stringOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST stringOption derived      (false|true) "false">
   <!ATTLIST stringOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT numericListOption EMPTY >
   <!ATTLIST numericListOption constant     (false|true) "false">
   <!ATTLIST numericListOption name         ID           #REQUIRED>
   <!ATTLIST numericListOption key          CDATA        #IMPLIED>
   <!ATTLIST numericListOption origin       CDATA        #IMPLIED>
   <!ATTLIST numericListOption description  CDATA        #IMPLIED>
   <!ATTLIST numericListOption toolTip      CDATA        "">
   <!ATTLIST numericListOption value        CDATA        "0">
   <!ATTLIST numericListOption size         CDATA        #IMPLIED>
   <!ATTLIST numericListOption min          CDATA        #IMPLIED>
   <!ATTLIST numericListOption max          CDATA        #IMPLIED>
   <!ATTLIST numericListOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST numericListOption derived      (false|true) "false">
   <!ATTLIST numericListOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT pinListOption EMPTY >
   <!ATTLIST pinListOption constant     (false|true) "false">
   <!ATTLIST pinListOption name         ID           #REQUIRED>
   <!ATTLIST pinListOption key          CDATA        #IMPLIED>
   <!ATTLIST pinListOption origin       CDATA        #IMPLIED>
   <!ATTLIST pinListOption description  CDATA        #IMPLIED>
   <!ATTLIST pinListOption toolTip      CDATA        "">
   <!ATTLIST pinListOption value        CDATA        "0">
   <!ATTLIST pinListOption size         CDATA        #IMPLIED>
   <!ATTLIST pinListOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST pinListOption derived      (false|true) "false">
   <!ATTLIST pinListOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT choiceOption (choice)* >
   <!ATTLIST choiceOption constant     (false|true) "false">
   <!ATTLIST choiceOption name         ID           #REQUIRED>
   <!ATTLIST choiceOption key          CDATA        #IMPLIED>
   <!ATTLIST choiceOption origin       CDATA        #IMPLIED>
   <!ATTLIST choiceOption description  CDATA        #IMPLIED>
   <!ATTLIST choiceOption toolTip      CDATA        "">
   <!ATTLIST choiceOption units        (None|Hz|Seconds)    "None">
   <!ATTLIST choiceOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST choiceOption derived      (false|true) "false">
   <!ATTLIST choiceOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT choice EMPTY >
   <!ATTLIST choice value        CDATA        #REQUIRED>
   <!ATTLIST choice name         CDATA        #REQUIRED>
   <!ATTLIST choice isDefault    (false|true) "false">

<!ELEMENT binaryOption (choice, choice) >
   <!ATTLIST binaryOption constant     (false|true) "false">
   <!ATTLIST binaryOption name         ID           #REQUIRED>
   <!ATTLIST binaryOption key          CDATA        #IMPLIED>
   <!ATTLIST binaryOption origin       CDATA        #IMPLIED>
   <!ATTLIST binaryOption description  CDATA        #IMPLIED>
   <!ATTLIST binaryOption toolTip      CDATA        "">
   <!ATTLIST binaryOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST binaryOption derived      (false|true) "false">
   <!ATTLIST binaryOption derivedFrom  IDREF        #IMPLIED>

<!ELEMENT template (#PCDATA)>
   <!ATTLIST template namespace (info|usbdm|class|all)  "info" >
   <!ATTLIST template name 		CDATA  				"" >
   <!ATTLIST template dim  		CDATA  				#IMPLIED >

<!ELEMENT validate (param*) >
   <!ATTLIST validate class CDATA #REQUIRED>
   
<!ELEMENT param EMPTY >
   <!ATTLIST param type  (long|string) #REQUIRED>
   <!ATTLIST param value CDATA         #REQUIRED>

<!ELEMENT signals EMPTY >
   <!ATTLIST signals name CDATA "" >

<!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList ((deleteResource|copy|constant)*) >
   <!ATTLIST projectActionList id          ID            #REQUIRED>
   <!ATTLIST projectActionList root        CDATA         #IMPLIED>
   <!ATTLIST projectActionList doOnceOnly  (true|false)  "true">
   
<!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
   <!ATTLIST excludeSourceFile target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFile excluded (true|false) "true" >

<!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
   <!ATTLIST excludeSourceFolder target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFolder excluded (true|false) "true" >

<!-- Remove file from Eclipse project -->
<!ELEMENT deleteResource EMPTY >
   <!ATTLIST deleteResource target  CDATA         #REQUIRED>

 <!ELEMENT createFolder EMPTY >
   <!ATTLIST createFolder target  CDATA #REQUIRED>
   <!ATTLIST createFolder type    (source|include|normal) "normal">

<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source               CDATA #REQUIRED>
   <!ATTLIST copy target               CDATA #REQUIRED>
   <!ATTLIST copy type                 CDATA #IMPLIED>
   <!ATTLIST copy sourcePathType       (absolute|relative|unknown) #IMPLIED>
   <!ATTLIST copy macroReplacement     (true|false) "true">
   <!ATTLIST copy replace              (true|false) "false">
   <!ATTLIST copy derived              (true|false) "false">
   
<!ELEMENT constant EMPTY >
   <!-- constant 
   key  	Allows specification of a explicit key rather than based upon the name.
   name 	In the absence of a key it is used to create a key tied to the current peripheral/file. 
            Used as visible name in GUI (model)
            Supports validation as an ID.
   weak		If true indicates the constant may already exist and this constant is discarded
   replace  Replaces any existing constant of the same key
   -->
   <!ATTLIST constant name         ID           #IMPLIED>
   <!ATTLIST constant key          CDATA        #IMPLIED>
   <!ATTLIST constant value        CDATA        #REQUIRED>
   <!ATTLIST constant type         (boolean|int|string)  "string" >
   <!ATTLIST constant weak         (true|false)          "false">
   <!ATTLIST constant replace      (true|false)          "false">
   
<!ELEMENT divider EMPTY >

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/uart0_mkl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devicePage SYSTEM "_menu.dtd" >
<!-- uart_mkl04.xml -->
<!--
Devices using this peripheral: 
-->
<devicePage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="UART">

   <aliasOption key="/SIM/sim_sopt2_uart$(_instance)src" optional="true" constant="false"  />
   <aliasOption key="/SIM/system_uart$(_instance)_clock" optional="true" />
   
   <category name="Advanced" description="Advanced options">
      <aliasOption key="/SIM/sim_sopt5_uart$(_instance)ode"   optional="true" constant="false" />
      <aliasOption key="/SIM/sim_sopt5_uart$(_instance)txsrc" optional="true" constant="false" />
      <aliasOption key="/SIM/sim_sopt5_uart$(_instance)rxsrc" optional="true" constant="false" />
   </category>

   <xi:include href="_irqOption.xml"/>

   <projectActionList id = "uart_files">
      <copy source="Project_Headers/uart.h"  target="Project_Headers/uart.h"  replace="true"  derived="true" />
   </projectActionList>
         
   <template><![CDATA[
   \tstatic constexpr bool statusNeedsWrite = true;\n\n
      
   \t/**
   \t * Get input clock frequency
   \t *
   \t * @return Input clock frequency as a uint32_t in Hz
   \t */
   \tstatic uint32_t getInputClockFrequency() {
   \t   return SimInfo::getUart0Clock();
   \t}\n\n
   ]]></template>

   <pins/>
</devicePage>

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/ftfa.xml
<?xml version="1.0" encoding="UTF-8"
?>
<!DOCTYPE devicePage SYSTEM "_menu.dtd" >
<!-- ftfl.xml -->

<devicePage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="Flash Memory Module" >

   <aliasOption key="pflash_sector_size" constant="true"
      description="Sector size for program flash (minimum erase element)"/>

   <aliasOption key="pflash_phrase_size" constant="true"
      description="Phrase size for program flash (minimum program element)"/>

   <projectActionList id = "flash_files" >
      <copy source="Project_Headers/flash.h"                 target="Project_Headers/flash.h"                 replace="true"  derived="true" />
      <copy source="Project_Headers/ftfa.h"                  target="Project_Headers/ftfa.h"                  replace="true"  derived="true" />
      <copy source="Sources/ftfa.cpp"                        target="Sources/ftfa.cpp"                        replace="true"  derived="true" />
      <copy source="Snippets/flash_programming_example.cpp"  target="Snippets/flash_programming_example.cpp"  replace="true"  derived="true" />
   </projectActionList>

   <constant name="FlashType" id="/Flash/FlashType" key="/Flash/FlashType" value="ftfa" />
   
   <template><![CDATA[
      \t// Sector size for program flash (minimum erase element)
      \tstatic constexpr unsigned programFlashSectorSize = $(pflash_sector_size);\n\n
   
      \t// Phrase size for program flash (minimum programming element)
      \tstatic constexpr unsigned programFlashPhraseSize = $(pflash_phrase_size);\n\n
         
   ]]></template>

</devicePage>

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/symbols/FRDM_KL46Z.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "../_menu.dtd" >
<!-- MK66F18_symbols.xml -->

<fragment xmlns:xi="http://www.w3.org/2001/XInclude">
   <!-- Definitions used by example programs -->
   <constant key="demo.cpp.led"                value="USBDM::GpioD&lt;5&gt;" /> <!-- Digital I/O generic LED -->
   <constant key="demo.cpp.pwm.led1"           value="tpm_LED_RED" />           <!-- FTM/TPM to LED -->
   <constant key="demo.cpp.pwm.led2"           value="tpm_LED_GREEN" />         <!-- FTM/TPM to LED -->
   <constant key="demo.cpp.red.led"            value="gpio_LED_RED" />          <!-- Digital I/O to LED -->
   <constant key="demo.cpp.green.led"          value="gpio_LED_GREEN" />        <!-- Digital I/O to LED -->
   <constant key="demo.cpp.blue.led"           value="gpio_LED_BLUE" />         <!-- Digital I/O to LED -->
   <constant key="demo.cpp.joystick.x"         value="adc_A2" />                <!-- Analogue I/O (Arduino) -->
   <constant key="demo.cpp.joystick.y"         value="adc_A1" />                <!-- Analogue I/O (Arduino) -->
   <constant key="demo.cpp.joystick.k"         value="gpio_A0" />               <!-- Digital I/O from switch (Arduino) -->
   <constant key="demo.cpp.external.switch"    value="gpio_A0" />               <!-- Digital I/O from switch (Arduino) -->
   <constant key="demo.cpp.external.led"       value="gpio_A1" />               <!-- Digital I/O to LED (Arduino) -->
   <constant key="demo.cpp.external.gps"       value="Gps2" />                  <!-- GPS module connected by serial -->
   <constant key="demo.cpp.external.spi"       value="Spi0" />                  <!-- SPI interface to off-board device -->
   <constant key="demo.cpp.external.i2c"       value="I2c1" />                  <!-- I2C interface to off-board device -->
   <constant key="demo.cpp.mma845x.i2c"        value="I2c0" />                  <!-- I2C interface to MMA845x -->
   <constant key="demo.cpp.fx0s8700cq.i2c"     value="I2c0" />                  <!-- I2C interface to FX0S8700CQ -->
   <constant key="demo.cpp.mag3110.i2c"        value="I2c0" />                  <!-- I2C interface to MAG3110 -->
   <constant key="demo.cpp.spi.dma"            value="new USBDM::DMAChannel0(), new USBDM::DMAChannel1()" />
   <constant key="demo.cpp.nrf24l01.spi"       value="Spi0Gpio" />              <!-- SPI interface to NRF24101 module -->
   <constant key="demo.cpp.nrf24l01.cs_n"      value="GpioD&lt;0&gt;" />        <!-- CS* connection to NRF24101 module -->
   <constant key="demo.cpp.nrf24l01.ce"        value="GpioD&lt;5&gt;" />        <!-- CE* connection to NRF24101 module -->
   <constant key="demo.cpp.nrf24l01.irq"       value="GpioA&lt;13&gt;" />       <!-- IRQ* connection from NRF24101 module -->
</fragment>

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/symbols/FRDM_K22F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "../_menu.dtd" >
<!-- MK22F51212_symbols.xml -->

<fragment xmlns:xi="http://www.w3.org/2001/XInclude">
   <!-- Definitions used by example programs -->
         <constant key="demo.cpp.led"                value="USBDM::GpioA&lt;1&gt;" /> <!-- Digital I/O generic LED -->
         <constant key="demo.cpp.pwm.led1"           value="ftm_LED_RED" />      <!-- FTM/TPM to LED -->
         <constant key="demo.cpp.pwm.led2"           value="ftm_LED_GREEN" />    <!-- FTM/TPM to LED -->
         <constant key="demo.cpp.red.led"            value="gpio_LED_RED" />     <!-- Digital I/O to LED -->
         <constant key="demo.cpp.green.led"          value="gpio_LED_GREEN" />   <!-- Digital I/O to LED -->
         <constant key="demo.cpp.blue.led"           value="gpio_LED_BLUE" />    <!-- Digital I/O to LED -->
         <constant key="demo.cpp.joystick.x"         value="adc_A2" />           <!-- Analogue I/O (Arduino) -->
         <constant key="demo.cpp.joystick.y"         value="adc_A1" />           <!-- Analogue I/O (Arduino) -->
         <constant key="demo.cpp.joystick.k"         value="gpio_A0" />          <!-- Digital I/O from switch (Arduino) -->
         <constant key="demo.cpp.external.switch"    value="gpio_A0" />          <!-- Digital I/O from switch (Arduino) -->
         <constant key="demo.cpp.external.led"       value="gpio_A1" />          <!-- Digital I/O to LED (Arduino) -->
         <constant key="demo.cpp.external.gps"       value="Gps2" />             <!-- GPS module connected by serial -->
         <constant key="demo.cpp.external.spi"       value="Spi1" />             <!-- SPI interface to off-board device -->
         <constant key="demo.cpp.external.i2c"       value="I2c1" />             <!-- I2C interface to off-board device -->
         <constant key="demo.cpp.mma845x.i2c"        value="I2c1" />             <!-- I2C interface to MMA845x -->
         <constant key="demo.cpp.fx0s8700cq.i2c"     value="I2c0" />             <!-- I2C interface to FX0S8700CQ -->
         <constant key="demo.cpp.mag3110.i2c"        value="I2c1" />             <!-- I2C interface to MAG3110 -->
         <constant key="demo.cpp.nrf24l01.spi"       value="Spi0" />             <!-- SPI interface to NRF24101 module -->
         <constant key="demo.cpp.nrf24l01.cs_n"      value="spi0_PCS1" />        <!-- CS* connection to NRF24101 module -->
         <constant key="demo.cpp.nrf24l01.ce"        value="GpioC&lt;11&gt;" />  <!-- CE* connection to NRF24101 module -->
         <constant key="demo.cpp.nrf24l01.irq"       value="GpioD&lt;0&gt;" />   <!-- IRQ* connection from NRF24101 module -->
</fragment>

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/ftfl32k.xml
<?xml version="1.0" encoding="UTF-8"
?>
<!DOCTYPE devicePage SYSTEM "_menu.dtd" >
<!-- ftfl.xml -->

<devicePage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="Flash Memory Module" >
   <choiceOption name="EepromSize" 
      description="FlexNVM - EEPROM size"
      toolTip="Selects EEPROM size">
      <choice value="eeprom32Bytes"  name="32 bytes" />
      <choice value="eeprom64Bytes"  name="64 bytes" />
      <choice value="eeprom128Bytes" name="128 bytes" />
      <choice value="eeprom256Bytes" name="256 bytes" />
      <choice value="eeprom512Bytes" name="512 bytes" />
      <choice value="eeprom1KBytes"  name="1K bytes" />
      <choice value="eeprom2KBytes"  name="2K bytes" isDefault="true"/>
   </choiceOption>
   
   <choiceOption name="FlashPartition" 
      description="FlexNVM - Flash EEPROM partition"
      toolTip="Selects division of FlexNVM between flash and EEPROM backing storage\n
               The larger the EEPROM backing the better the wear characteristic">
      <choice value="partition_flash64K_eeprom0K" name="flash=64K eeprom=0K" />
      <choice value="partition_flash32K_eeprom32K" name="flash=32K eeprom=32K" />
      <choice value="partition_flash0K_eeprom64K" name="flash=0K eeprom=64K" isDefault="true"/>
   </choiceOption>
   
   <choiceOption name="FlexNVM_Partition" 
      description="FlexNVM - EEPROM partition"
      toolTip="Selects division of the two regions of EEPROM (if supported on device)\n
               This allows A/B regions to have different wear characteristics">
      <choice value="partition_A1_B7_8ths" name="A=1/8, B=7/8" />
      <choice value="partition_A2_B6_8ths" name="A=1/4, B=3/4" />
      <choice value="partition_A4_B4_8ths" name="A=1/2, B=1/2" isDefault="true"/>
   </choiceOption>

   <projectActionList id = "flash_files" >
      <copy source="Project_Headers/flash.h" target="Project_Headers/flash.h" replace="true"  derived="true" />
      <copy source="Project_Headers/ftfl.h"  target="Project_Headers/ftfl.h"  replace="true"  derived="true" />
      <copy source="Sources/ftfl.cpp"        target="Sources/ftfl.cpp"        replace="true"  derived="true" />
   </projectActionList>

   <constant name="FlashType" id="/Flash/FlashType" key="/Flash/FlashType" value="ftfl" />
   
   <template><![CDATA[
      \t/** Selects EEPROM size */
      \tenum EepromSel {
      \t   eeprom32Bytes,
      \t   eeprom64Bytes,
      \t   eeprom128Bytes,
      \t   eeprom256Bytes,
      \t   eeprom512Bytes,
      \t   eeprom1KBytes,
      \t   eeprom2KBytes,
      \t};\n\n
      
      \t/** Selects division of FlexNVM between flash and EEPROM backing storage */
      \tenum PartitionSel {
      \t   partition_flash32K_eeprom0K,
      \t   partition_flash24K_eeprom8K,
      \t   partition_flash16K_eeprom16K,
      \t   partition_flash8K_eeprom24K,
      \t   partition_flash0K_eeprom32K,

      \t   // All EEPROM
      \t   partition_flash0K_eeprom_all = partition_flash0K_eeprom32K,
      \t};\n\n
      
      \t/**
      \t * Selects division of the two regions of EEPROM (if supported on device)
      \t * This allows A/B regions to have different wear characteristics
      \t */
      \tenum PartitionSplit {
      \t   partition_default=0x30, //! Single partition
      \t};\n\n
   
      \t//! FlexNVM - EEPROM size
      \tstatic constexpr EepromSel eepromSel = $(EepromSize);\n\n

      \t//! FlexNVM - Flash EEPROM partition
      \tstatic constexpr PartitionSel partitionSel = $(FlashPartition);\n\n

      \t//! FlexNVM - EEPROM partition
      \tstatic constexpr PartitionSplit partitionSplit = $(FlexNVM_Partition);\n\n
   ]]></template>

</devicePage>

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/_examples.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "_menu.dtd" >
<!-- examples.xml -->

<fragment xmlns:xi="http://www.w3.org/2001/XInclude">
   <menu name="OSC0" description="Oscillator">
   
      <aliasOption key="system_mcgir_clock" />
   
      <choiceOption name="XXXX" description="YYYYY"
         toolTip="ZZZZZZZ">
         <choice value="0" name="AAAA" />
         <choice value="1" name="BBBB" />
         <choice value="2" name="CCCC" />
         <choice value="3" name="DDDD" />
      </choiceOption>

      <binaryOption name="XXXXX" description="YYYYY"
         toolTip="TTTTTTTTTTTT">
         <choice value="0" name="111111111111" />
         <choice value="1" name="222222222222" />
      </binaryOption>

      <intOption name="xxxx" description="yyyyyy" toolTip="yyyyyyy"
         value="4000000" constant="true" />
   </menu>
</fragment>

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/uart0_mkl04z4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "_menu.dtd" >
<!-- uart_mkl04.xml -->
<!--
Devices using this peripheral: 
-->
<devicePage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="UART">

   <aliasOption key="/SIM/sim_sopt2_uart$(_instance)src" optional="true" constant="false"  />
   <aliasOption key="/SIM/system_uart$(_instance)_clock" optional="true" />
   
   <menu name="Advanced" description="Advanced options">
      <aliasOption key="/SIM/sim_sopt5_uart$(_instance)ode"   optional="true" constant="false" />
      <aliasOption key="/SIM/sim_sopt5_uart$(_instance)txsrc" optional="true" constant="false" />
      <aliasOption key="/SIM/sim_sopt5_uart$(_instance)rxsrc" optional="true" constant="false" />
   </menu>

   <xi:include href="_irqOption.xml"/>

   <projectActionList id = "uart_files">
      <copy source="Project_Headers/uart.h"  target="Project_Headers/uart.h"  replace="true"  derived="true" />
   </projectActionList>
         
   <template>
      \tstatic constexpr bool statusNeedsWrite = true;\n\n
      
      \t/**
      \t * Get input clock frequency
      \t *
      \t * @return Input clock frequency as a uint32_t in Hz
      \t */
      \tstatic uint32_t getInputClockFrequency() {
      \t
      \t   switch(SIM-&gt;SOPT2&amp;SIM_SOPT2_UART0SRC_MASK) {
      \t   default:
      \t   case SIM_SOPT2_UART0SRC(0): return 0;
      \t   case SIM_SOPT2_UART0SRC(1): return SystemPeripheralClock;
      \t   case SIM_SOPT2_UART0SRC(2): return SystemMcgFllClock;
      \t   case SIM_SOPT2_UART0SRC(3): return SystemMcgirClock;
      \t   }
      \t}\n\n
   </template>

   <pins/>
</devicePage>
