=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/Menu.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root fileElement -->
<!ELEMENT root (menu*,validate*,template) >
   <!ATTLIST root xmlns:xi CDATA #IMPLIED>

<!ELEMENT menu ((intOption|choiceOption|binaryOption|xi:include|menu)*) >
   <!ATTLIST menu xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST menu name         CDATA        #REQUIRED>
   <!ATTLIST menu description  CDATA        #REQUIRED>
   
<!ELEMENT intOption EMPTY >
   <!ATTLIST intOption name         CDATA        #REQUIRED>
   <!ATTLIST intOption description  CDATA        #REQUIRED>
   <!ATTLIST intOption toolTip      CDATA        "">
   <!ATTLIST intOption value        CDATA        "0">
   <!ATTLIST intOption min          CDATA        "0">
   <!ATTLIST intOption max          CDATA        "0x7fffffffffffffff">
   <!ATTLIST intOption step         CDATA        "1">
   <!ATTLIST intOption constant     (false|true) "false">
  
<!ELEMENT choiceOption (choice)* >
   <!ATTLIST choiceOption name         CDATA        #REQUIRED>
   <!ATTLIST choiceOption description  CDATA        #REQUIRED>
   <!ATTLIST choiceOption toolTip      CDATA        "">
  
<!ELEMENT choice EMPTY >
   <!ATTLIST choice value        CDATA        #REQUIRED>
   <!ATTLIST choice name         CDATA        #REQUIRED>
   <!ATTLIST choice isDefault    (false|true) "false">

<!ELEMENT binaryOption (choice, choice) >
   <!ATTLIST binaryOption name         CDATA        #REQUIRED>
   <!ATTLIST binaryOption description  CDATA        #REQUIRED>
   <!ATTLIST binaryOption toolTip      CDATA        "">

<!ELEMENT xi:include EMPTY>
   <!ATTLIST xi:include href      CDATA        #REQUIRED>

<!ELEMENT template (#PCDATA)>
   <!ELEMENT validate (param*) >
   <!ATTLIST validate class CDATA #REQUIRED>
   
<!ELEMENT param EMPTY >
   <!ATTLIST param type  (int|string) #REQUIRED>
   <!ATTLIST param value CDATA        #REQUIRED>

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/Spi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "Menu.dtd" >
<!-- ftm.xml -->

<root xmlns:xi="http://www.w3.org/2001/XInclude">
   <page name="_instance" description="Serial Peripheral Interface">
   
      <choiceOption name="MODE" description="Mode"
         toolTip="Communication mode">
         <choice value="0" name="Mode 0: CPOL=0, CPHA=0" />
         <choice value="1" name="Mode 1: CPOL=0, CPHA=1" />
         <choice value="2" name="Mode 2: CPOL=1, CPHA=0" />
         <choice value="3" name="Mode 3: CPOL=1, CPHA=1" />
         <choice value="1" name="Default" />
      </choiceOption>

      <intOption name="SPEED" description="Speed"
         toolTip="Speed of transmission"
         value="100000" min="0" max="10000000" />

      <binaryOption name="LSBFE" description="Transmission order"
         toolTip="Transmission order">
         <choice value="0" name="MSB first" />
         <choice value="1" name="LSB first" />
      </binaryOption>

   </page>
   <template>
      #ifdef SPI_CTAR_LSBFE_SHIFT\n
      \t//! Default communication mode: order, clock phase and clock polarity\n
      \tstatic constexpr uint32_t modeValue = ($(LSBFE)&lt;&lt;SPI_CTAR_LSBFE_SHIFT)|($(MODE)&lt;&lt;SPI_CTAR_CPHA_SHIFT);\n\n
      #endif\n
      \t//! Default speed (Hz)\n
      \tstatic constexpr uint32_t speed = $(SPEED);\n\n
   </template>
</root>

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/sim_mk65f18.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "Menu.dtd" >
<!-- sim_mk65f18.xml -->
<!--
Devices using this peripheral: 
-->
<root xmlns:xi="http://www.w3.org/2001/XInclude">
   <page name="_instance" description="SIM">
   
      <choiceOption name="sim_sopt1_osc32ksel" 
         description="ERCLK32K source"
         toolTip="Clock source of External 32k Reference Clock [ERCLK32K]">
         <choice value="0"  name="System oscillator in low range (OSC32KCLK)" />
         <choice value="1"  name="Reserved" />
         <choice value="2"  name="RTC 32kHz clock" isDefault="true" />
         <choice value="3"  name="LPO 1kHz clock" />
      </choiceOption>
      
      <binaryOption name="sim_sopt2_rtcclkoutsel" 
         description="RTC clock out select [RTC_CLKOUT pin]"
         toolTip="Clock output on the RTC_CLKOUT pin">
         <choice value="0"  name="RTC 1 Hz clock" />
         <choice value="1"  name="RTC 32.768kHz clock" isDefault="true" />
      </binaryOption>

      <choiceOption name="sim_sopt2_lpuartsrc" 
         description="LPUART clock source select"
         toolTip="Selects the clock source for the LPUART transmit and receive clock">
         <choice value="0"  name="Disabled" isDefault="true" />
         <choice value="1"  name="PLL/FLL clock after division by CLKDIV3" />
         <choice value="2"  name="OSCERCLK clock" />
         <choice value="3"  name="MCGIRCLK clock" />
      </choiceOption>

      <choiceOption name="sim_sopt2_tpmsrc" 
         description="TPM clock source select"
         toolTip="Selects the clock source for the TPM counter clock">
         <choice value="0"  name="Disabled" isDefault="true" />
         <choice value="1"  name="PLL/FLL clock after division by CLKDIV3" />
         <choice value="2"  name="OSCERCLK clock" />
         <choice value="3"  name="MCGIRCLK clock" />
      </choiceOption>

      <choiceOption name="sim_sopt2_usbsrc" 
         description="USB clock source select"
         toolTip="Selects the clock source for the TPM counter clock">
         <choice value="0"  name="External bypass clock (USB_CLKIN)" isDefault="true" />
         <choice value="1"  name="PLL/FLL clock" isDefault="true" />
      </choiceOption>

      <choiceOption name="sim_sopt2_pllfllsel" 
         description="PLL/FLL clock select (to LPUART, TPM etc.)"
         toolTip="Selects the clock for various peripherals.">
         <choice value="0"  name="MCGFLLCLK clock" isDefault="true" />
         <choice value="1"  name="MCGPLLCLK clock" />
         <choice value="2"  name="USB1 PFD clock (some devices only)" />
         <choice value="3"  name="IRC48 MHz clock (some devices only)" />
      </choiceOption>

      <menu name="sim_clkdiv1" description="Clock Dividers">
         <intOption name="sim_clkdiv1_outdiv1" 
            constant="true"
            description="Core &amp; System Clock Divider (OUTDIV1) - Divide by [1-16]"
            toolTip="Clocks the ARM Cortex-M4 core and bus masters [SIM_CLKDIV1_OUTDIV1]\n
                     Divides MCGOUT Clock to generate system_core_clock"
            value="1" offset="-1" min="1" max="16" />
      
         <intOption name="sim_clkdiv1_outdiv2" 
            constant="true"
            description="Bus Clock Divider (OUTDIV2) - Divide by [1-16]"
            toolTip="Clocks the bus slaves and peripheral [SIM_CLKDIV1_OUTDIV2]\n
               Divides MCGOUT Clock to generate system_bus_clock\n
               MCGOUTCLK clock is source. Default /2"
            value="1" offset="-1" min="1" max="16" />
      
         <intOption name="sim_clkdiv1_outdiv3" 
            constant="true"
            description="Flexbus Clock Divider (OUTDIV3) - Divide by [1-16]"
            toolTip="Clocks the flexbus interface [SIM_CLKDIV1_OUTDIV3]\n
                     Divides MCGOUT Clock to generate system_flexbus_clock\n
                     MCGOUTCLK clock is source. Default /2"
            value="1" offset="-1" min="1" max="16" />
      
         <intOption name="sim_clkdiv1_outdiv4" 
            constant="true"
            description="Flash Clock Divider (OUTDIV4) - Divide by [1-16]"
            toolTip="Clocks the flash memory [SIM_CLKDIV1_OUTDIV4]\n
                     Divides MCGOUT Clock to generate system_flash_clock\n
                     MCGOUTCLK clock is source. Default /4"
            value="4" offset="-1" min="1" max="16" />
      </menu>
      <choiceOption name="sim_clkdiv2_usb"
         description="USB clock divider" 
         toolTip="Sets the clock divider when the MCGFLLCLK, MCGPLLCLK, or IRC48M clock\n
         is the USB clock source.">
         <choice value="1" name="Multiply by 2 (div=0, frac=1)" />
         <choice value="0" name="Multiply by 1 (div=0, frac=0)" />
         <choice value="3" name="Multiply by 1 (div=1, frac=1)" />
         <choice value="5" name="Divide by 1.5 (div=2, frac=1)" />
         <choice value="2" name="Divide by 2 (div=1, frac=0)" />
         <choice value="7" name="Divide by 2 (div=3, frac=1)" />
         <choice value="9" name="Divide by 2.5 (div=4, frac=1)" />
         <choice value="4" name="Divide by 3 (div=2, frac=0)" />
         <choice value="11" name="Divide by 3 (div=5, frac=1)" />
         <choice value="13" name="Divide by 3.5 (div=6, frac=1)" />
         <choice value="6" name="Divide by 4 (div=3, frac=0)" />
         <choice value="15" name="Divide by 4 (div=7, frac=1)" />
         <choice value="8" name="Divide by 5 (div=4, frac=0)" />
         <choice value="10" name="Divide by 6 (div=5, frac=0)" />
         <choice value="12" name="Divide by 7 (div=6, frac=0)" />
         <choice value="14" name="Divide by 8 (div=7, frac=0)" />
      </choiceOption>

      <choiceOption name="sim_clkdiv3_pllfll"
         description="PLL/FLL clock divider" 
         toolTip="Selects the clock divider for various peripherals.">
         <choice value="1" name="Multiply by 2 (div=0, frac=1)" />
         <choice value="0" name="Multiply by 1 (div=0, frac=0)" />
         <choice value="3" name="Multiply by 1 (div=1, frac=1)" />
         <choice value="5" name="Divide by 1.5 (div=2, frac=1)" />
         <choice value="2" name="Divide by 2 (div=1, frac=0)" />
         <choice value="7" name="Divide by 2 (div=3, frac=1)" />
         <choice value="9" name="Divide by 2.5 (div=4, frac=1)" />
         <choice value="4" name="Divide by 3 (div=2, frac=0)" />
         <choice value="11" name="Divide by 3 (div=5, frac=1)" />
         <choice value="13" name="Divide by 3.5 (div=6, frac=1)" />
         <choice value="6" name="Divide by 4 (div=3, frac=0)" />
         <choice value="15" name="Divide by 4 (div=7, frac=1)" />
         <choice value="8" name="Divide by 5 (div=4, frac=0)" />
         <choice value="10" name="Divide by 6 (div=5, frac=0)" />
         <choice value="12" name="Divide by 7 (div=6, frac=0)" />
         <choice value="14" name="Divide by 8 (div=7, frac=0)" />
      </choiceOption>

   </page>

   <projectActionList id = "sim_files" >
   </projectActionList>
         
   <template>
      \t//! System Options Register 1
      \tstatic constexpr uint32_t sim_sopt1 = 
      \t   SIM_SOPT1_OSC32KSEL($(sim_sopt1_osc32ksel)); // 32K oscillator clock select\n\n
      
      \t//! System Options Register 2
      \tstatic constexpr uint32_t sim_sopt2 = 
      \t   SIM_SOPT2_RTCCLKOUTSEL($(sim_sopt2_rtcclkoutsel)) | // RTC clock out select
      \t   SIM_SOPT2_LPUARTSRC($(sim_sopt2_lpuartsrc)) |    // LPUART clock source select
      \t   SIM_SOPT2_TPMSRC($(sim_sopt2_tpmsrc)) |       // TPM clock source select
      \t   SIM_SOPT2_USBSRC($(sim_sopt2_usbsrc)) |       // USB clock source select
      \t   SIM_SOPT2_PLLFLLSEL($(sim_sopt2_pllfllsel));     // PLL/FLL clock select\n\n

      \t//! System Clock Divider Register 1
      \tstatic constexpr uint32_t sim_clkdiv1 = 
      \t   SIM_CLKDIV1_OUTDIV4($(sim_clkdiv1_outdiv4))|  // Core/system clock
      \t#ifdef SIM_CLKDIV1_OUTDIV3
      \t   SIM_CLKDIV1_OUTDIV3($(sim_clkdiv1_outdiv3))|  // FlexBus clock (if present)
      \t#endif
      \t   SIM_CLKDIV1_OUTDIV2($(sim_clkdiv1_outdiv2))|  // Bus clock
      \t   SIM_CLKDIV1_OUTDIV1($(sim_clkdiv1_outdiv1));  // Core/system clock \n\n
      
      \t//! System Clock Divider Register 2
      \tstatic constexpr uint32_t sim_clkdiv2 = 
      \t   $(sim_clkdiv2_usb);  // USB clock divider divisor &amp; fraction \n\n
      
      \t//! System Clock Divider Register 3
      \tstatic constexpr uint32_t sim_clkdiv3 = 
      \t   $(sim_clkdiv3_pllfll);  // PLLFLL clock divider divisor &amp; fraction \n\n
      
   </template>
</root>

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/cmp0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "Menu.dtd" >
<!-- Cmp0.xml -->

<root xmlns:xi="http://www.w3.org/2001/XInclude">
   <page name="_instance" description="Comparitor">
   
      <choiceOption name="cmp_cr0_filter_cnt" 
         description="Filter Sample Count"
         toolTip="Represents the number of consecutive samples that must agree prior\n
         to the comparator ouput filter accepting a new output state.">
         <choice value="0" name="Filter is disabled" />
         <choice value="1" name="1 sample must agree" />
         <choice value="2" name="2 sample must agree" />
         <choice value="3" name="3 sample must agree" />
         <choice value="4" name="4 sample must agree" />
         <choice value="5" name="5 sample must agree" />
         <choice value="6" name="6 sample must agree" />
         <choice value="7" name="7 sample must agree" />
      </choiceOption>

      <choiceOption name="cmp_cr0_hystctr" 
         description="Comparator hard block hysteresis control"
         toolTip="Defines the programmable hysteresis level.\n
         The hysteresis values associated with each level are device specific">
         <choice value="0" name="Level 0" />
         <choice value="1" name="Level 1" />
         <choice value="2" name="Level 2" />
         <choice value="3" name="Level 3" />
      </choiceOption>

      <binaryOption name="cmp_cr1_se" 
         description="Sample Enable"
         toolTip="Sampling mode enabled">
         <choice value="0" name="Sampling mode is disabled" />
         <choice value="1" name="Sampling mode is enabled" />
      </binaryOption>

      <binaryOption name="cmp_cr1_we" 
         description="Windowing Enable"
         toolTip="Windowing mode enabled">
         <choice value="0" name="Windowing mode is disabled" />
         <choice value="1" name="Windowing mode is enabled" />
      </binaryOption>

      <binaryOption name="cmp_cr1_trigm" 
         description="Trigger Mode Enable"
         toolTip="CMP and DAC are configured to CMP Trigger mode">
         <choice value="0" name="Trigger mode is disabled" />
         <choice value="1" name="Trigger mode is enabled" />
      </binaryOption>

      <binaryOption name="cmp_cr1_pmode" 
         description="Power Mode Select"
         toolTip="Selects trade-off between speed and power consumption">
         <choice value="0" name="Low-Speed (LS) Comparison mode" />
         <choice value="1" name="High-Speed (HS) Comparison mode" />
      </binaryOption>

      <binaryOption name="cmp_cr1_inv" 
         description="Comparator Invert"
         toolTip="Allows selection of the polarity of the analog comparator function.">
         <choice value="0" name="Not inverted" />
         <choice value="1" name="Inverted" />
      </binaryOption>

      <binaryOption name="cmp_cr1_cos" 
         description="Comparator Output Select"
         toolTip="">
         <choice value="0" name="Set the filtered comparator output (CMPO) to equal COUT" />
         <choice value="1" name="Set the unfiltered comparator output (CMPO) to equal COUTA" />
      </binaryOption>

      <binaryOption name="cmp_cr1_ope" 
         description="Comparator Output Pin Enable"
         toolTip="">
         <choice value="0" name="CMPO is not available on CMPO pin" />
         <choice value="1" name="CMPO is available on CMPO pin" />
      </binaryOption>

      <binaryOption name="cmp_cr1_en" 
         description="Comparator Module Enable"
         toolTip="Enables the Analog Comparator module">
         <choice value="0" name="Analog Comparator is disabled" />
         <choice value="1" name="Analog Comparator is enabled" />
      </binaryOption>

      <intOption name="cmp_fpr_filt_per"
         description="Filter Sample Period"
         toolTip="Specifies the sampling period, in bus clock cycles, of the comparator output filter"
         value="0" min="0" max="255" />
         
      <binaryOption name="IRQ_HANDLER" description="Handler for IRQ"
         toolTip="The interrupt handler may be a static member function or\n
         may be set by use of the setCallback() method" >
         <choice value="false" name="No handler installed" />
         <choice value="true" name="Handler installed" />
      </binaryOption>

      <intOption name="IRQ_LEVEL" description="IRQ Level in NVIC [0-15]"
         toolTip="Sets the priority level used to configure the NVIC"
         value="0" min="0" max="15" />
         
      <pins/>
   </page>
   
   <template>
      \t//! Indicates interrupt handler has been installed
      \tstatic constexpr bool irqHandlerInstalled = $(IRQ_HANDLER);\n\n
      
      \t//! Default IRQ level\n
      \tstatic constexpr uint32_t irqLevel =  $(IRQ_LEVEL);\n\n
      
      \t//! Frequency of RTC External Clock or Crystal\n
      \tstatic constexpr uint32_t rtcclk_clock = $(rtcclk_clock)UL;\n\n
      
      \t//! CMP Control Register 0\n
      \tstatic constexpr uint32_t CMP_CR0 =
      \t   CMP_CR0_FILTER_CNT($(cmp_cr0_filter_cnt))     | // Filter Sample Count
      \t   CMP_CR0_FILTER_HYSTCTR($(cmp_cr0_hystctr));  // Comparator hard block hysteresis control\n\n
      
      \t//! CMP Control Register 1\n
      \tstatic constexpr uint32_t CMP_CR1 =
      \t   CMP_CR1_SE($(cmp_cr1_se))    | // Sample Enable
      \t   CMP_CR1_WE($(cmp_cr1_we))    | // Windowing Enable
      \t   CMP_CR1_TRIGM($(cmp_cr1_trigm)) | // Trigger Mode Enable
      \t   CMP_CR1_PMODE($(cmp_cr1_pmode)) | // Power mode Select
      \t   CMP_CR1_INV($(cmp_cr1_inv))   | // Comparator Invert
      \t   CMP_CR1_COS($(cmp_cr1_cos))   | // Comparator Output Select
      \t   CMP_CR1_OPE($(cmp_cr1_ope))   | // Comparator Output Pin Enable
      \t   CMP_CR1_EN($(cmp_cr1_en));     // Comparator Module Enable\n\n
      
      \t//! CMP Filter Period Register\n
      \tstatic constexpr uint32_t CMP_FPR =
      \t   CMP_FPR_FILT_PER($(cmp_fpr_filt_per)); // Filter Sample Period\n\n
      
   </template>
</root>

=== PatrickFulcheri/usbdm-eclipse-plugins/net.sourceforge.usbdm.deviceEditor/hardware/peripherals/pit_4ch_def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "Menu.dtd" >
<!-- pit.xml -->

<root xmlns:xi="http://www.w3.org/2001/XInclude">
   <page name="_instance" description="Programmable Interrupt Timer">

      <intOption name="pit_ldval" description="Reload value [0-65535]"
         toolTip="Value loaded in timer register on roll-over"
         value="10000" min="0" max="65535" />

      <binaryOption name="pit_mcr_frz" description="Freeze in debug mode"
         toolTip="Controls whether the timer continues to run in debug mode">
         <choice value="0" name="Timers continue to run in debug mode" />
         <choice value="1" name="Timers are stopped in Debug mode" />
      </binaryOption>

      <binaryOption name="pit_tctrl_ch1" description="Chain timers 1-0"
         toolTip="Controls whether the timer channels are chained to creater a larger counter">
         <choice value="0" name="Timers are not chained" />
         <choice value="1" name="Timers are chained" />
      </binaryOption>

      <binaryOption name="pit_tctrl_ch3" description="Chain timers 3-2"
         toolTip="Controls whether the timer channels are chained to creater a larger counter">
         <choice value="0" name="Timers are not chained" />
         <choice value="1" name="Timers are chained" />
      </binaryOption>

      <binaryOption name="irq0Handler" description="Handler for channel 0"
         toolTip="The interrupt handler may be a static member function or\n
         may be set by use of the setCallback() method">
         <choice value="0" name="No handler installed" />
         <choice value="1" name="Handler installed" />
      </binaryOption>

      <binaryOption name="irq1Handler" description="Handler for channel 1"
         toolTip="The interrupt handler may be a static member function or\n
         may be set by use of the setCallback() method">
         <choice value="0" name="No handler installed" />
         <choice value="1" name="Handler installed" />
      </binaryOption>

      <binaryOption name="irq2Handler" description="Handler for channel 2"
         toolTip="The interrupt handler may be a static member function or\n
         may be set by use of the setCallback() method">
         <choice value="0" name="No handler installed" />
         <choice value="1" name="Handler installed" />
      </binaryOption>

      <binaryOption name="irq3Handler" description="Handler for channel 3"
         toolTip="The interrupt handler may be a static member function or\n
         may be set by use of the setCallback() method">
         <choice value="0" name="No handler installed" />
         <choice value="1" name="Handler installed" />
      </binaryOption>

      <intOption name="irqLevel" description="IRQ Level in NVIC [0-15]"
         toolTip="Sets the priority level used to configure the NVIC"
         value="0" min="0" max="15" />
   </page>
   
   <projectActionList id = "lptmr0_0" >
      <copy source="Snippets/pit-example1.cpp"       target="Snippets/pit-example1.cpp" />
      <copy source="Snippets/pit-example2-MK.cpp"    target="Snippets/pit-example2.cpp" />
      <copy source="Project_Headers/pit-MK.h"        target="Project_Headers/pit.h"        replace="true" derived="true" />
   </projectActionList>
         
   <template>
      \t//! Default value for PIT->SC register\n
      \tstatic constexpr uint32_t loadValue  = 
      \t   $(pit_ldval);\n\n
      
      \t//! PIT operation in debug mode\n
      \tstatic constexpr uint32_t mcr = 
      \t   PIT_MCR_FRZ($(pit_mcr_frz));\n\n
      
      \t//! Default IRQ level\n
      \tstatic constexpr uint32_t irqLevel =  $(irqLevel);\n\n
   </template>
</root>
